default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: server_development

test:
  <<: *default
  database: server_test

production:
  <<: *default
  database: server_production
  username: <%= Rails.application.credentials.dig(:mysql, :username) %>
  password: <%= Rails.application.credentials.dig(:mysql, :password) %>
  host: <%= Rails.application.credentials.dig(:mysql, :host) %>
  port: <%= Rails.application.credentials.dig(:mysql, :port) %>
